# API Gateway for Cloud-Native Microservices Platform
# Provides centralized routing, rate limiting, authentication, and load balancing

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-gateway-config
  namespace: default
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream user-service {
            server user-service:80;
        }
        
        upstream catalog-service {
            server catalog-service:80;
        }
        
        upstream order-service {
            server order-service:80;
        }
        
        upstream predictor-service {
            server predictor-service:80;
        }
        
        upstream cost-optimizer {
            server cost-optimizer:80;
        }
        
        # Rate limiting zones
        limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;
        limit_req_zone $binary_remote_addr zone=ml_limit:10m rate=2r/s;
        
        # Logging format
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                       '$status $body_bytes_sent "$http_referer" '
                       '"$http_user_agent" "$http_x_forwarded_for" '
                       'rt=$request_time uct="$upstream_connect_time" '
                       'uht="$upstream_header_time" urt="$upstream_response_time"';
        
        server {
            listen 80;
            server_name api-gateway;
            access_log /var/log/nginx/access.log main;
            
            # Health check endpoint
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
            
            # API Documentation
            location /docs {
                return 200 '
                {
                  "api_version": "v1",
                  "services": {
                    "user-service": "/api/v1/users/*",
                    "catalog-service": "/api/v1/products/*", 
                    "order-service": "/api/v1/orders/*",
                    "predictor-service": "/api/v1/predictions/*",
                    "cost-optimizer": "/api/v1/cost/*"
                  },
                  "rate_limits": {
                    "standard_apis": "10 requests/second",
                    "ml_apis": "2 requests/second"
                  }
                }';
                add_header Content-Type application/json;
            }
            
            # User Service Routes
            location /api/v1/users {
                limit_req zone=api_limit burst=20 nodelay;
                proxy_pass http://user-service/users;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                # CORS headers
                add_header Access-Control-Allow-Origin *;
                add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
                add_header Access-Control-Allow-Headers "Content-Type, Authorization";
            }
            
            # Catalog Service Routes  
            location /api/v1/products {
                limit_req zone=api_limit burst=30 nodelay;
                proxy_pass http://catalog-service/products;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                add_header Access-Control-Allow-Origin *;
                add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
                add_header Access-Control-Allow-Headers "Content-Type, Authorization";
            }
            
            # Order Service Routes
            location /api/v1/orders {
                limit_req zone=api_limit burst=25 nodelay;
                proxy_pass http://order-service/orders;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                add_header Access-Control-Allow-Origin *;
                add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
                add_header Access-Control-Allow-Headers "Content-Type, Authorization";
            }
            
            # ML Prediction Routes (Lower rate limit)
            location /api/v1/predictions {
                limit_req zone=ml_limit burst=5 nodelay;
                proxy_pass http://predictor-service/predict;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_read_timeout 30s;
                
                add_header Access-Control-Allow-Origin *;
                add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
                add_header Access-Control-Allow-Headers "Content-Type, Authorization";
            }
            
            # Cost Analysis Routes
            location /api/v1/cost {
                limit_req zone=ml_limit burst=3 nodelay;
                proxy_pass http://cost-optimizer/cost-analysis;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                add_header Access-Control-Allow-Origin *;
                add_header Access-Control-Allow-Methods "GET, OPTIONS";
                add_header Access-Control-Allow-Headers "Content-Type, Authorization";
            }
            
            # Metrics endpoint (restricted)
            location /metrics {
                allow 10.0.0.0/8;
                allow 172.16.0.0/12;
                allow 192.168.0.0/16;
                deny all;
                
                proxy_pass http://predictor-service/metrics;
                proxy_set_header Host $host;
            }
            
            # Default route - API overview
            location / {
                return 200 '
                {
                  "message": "Cloud-Native Microservices Platform API Gateway",
                  "version": "1.0.0",
                  "documentation": "/docs",
                  "health": "/health",
                  "endpoints": {
                    "users": "/api/v1/users",
                    "products": "/api/v1/products",
                    "orders": "/api/v1/orders", 
                    "predictions": "/api/v1/predictions",
                    "cost_analysis": "/api/v1/cost"
                  }
                }';
                add_header Content-Type application/json;
            }
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: default
  labels:
    app: api-gateway
    tier: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        tier: gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: nginx
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      # Nginx exporter for metrics
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.10.0
        args:
        - -nginx.scrape-uri=http://localhost:80/nginx_status
        ports:
        - containerPort: 9113
          name: metrics
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-gateway-config
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: default
  labels:
    app: api-gateway
    tier: gateway
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: metrics
      port: 9113
      targetPort: 9113
      protocol: TCP
  type: LoadBalancer

---
# HPA for API Gateway
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 200
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60