apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudproject-microservices
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Daksh-khandelwal-1495/TecdiaAutomation.git'
    path: '.'
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
